In [2]:
import torch.nn as nn
import torch

/home/siegfriedlein/anaconda3/envs/keypoint-detection/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.rand(1, 3, 256, 256, dtype=torch.float32)
target = torch.rand(1, 3, 256, 256, dtype=torch.float32)
output = loss(m(input), target)
print(input)
print(target)
print(output)
output = loss(target, target)
print(output)
sm = m(input)
output = loss(sm, sm)
print(output)

tensor([[[[0.6770, 0.7290, 0.4426,  ..., 0.1475, 0.3183, 0.6815],
          [0.2718, 0.1464, 0.4735,  ..., 0.5662, 0.8343, 0.9359],
          [0.7134, 0.6968, 0.2501,  ..., 0.2057, 0.1285, 0.8711],
          ...,
          [0.3881, 0.8487, 0.2487,  ..., 0.6716, 0.6524, 0.3760],
          [0.4018, 0.6398, 0.5323,  ..., 0.1964, 0.9612, 0.6381],
          [0.1710, 0.5693, 0.2868,  ..., 0.6645, 0.2239, 0.5372]],

         [[0.4159, 0.9627, 0.5786,  ..., 0.8984, 0.6722, 0.0027],
          [0.1415, 0.6999, 0.9243,  ..., 0.1757, 0.0584, 0.6825],
          [0.5299, 0.9428, 0.4477,  ..., 0.8724, 0.1643, 0.1590],
          ...,
          [0.2004, 0.9171, 0.1459,  ..., 0.6219, 0.6791, 0.3318],
          [0.8294, 0.8087, 0.3835,  ..., 0.8852, 0.4337, 0.3737],
          [0.0794, 0.4983, 0.6962,  ..., 0.0260, 0.2936, 0.8140]],

         [[0.1973, 0.8971, 0.3559,  ..., 0.2776, 0.2019, 0.3385],
          [0.8295, 1.0000, 0.8751,  ..., 0.7162, 0.1960, 0.3980],
          [0.6984, 0.0700, 0.9868,  ..., 0

In [79]:
input = torch.empty(8,8).random_(2)
#input = torch.randn(3, 5, requires_grad=True)
print(input)
input_soft = torch.softmax(torch.softmax(input, dim =1), dim=0)
input_tanh = torch.tanh(input)
print(input_soft)
print(input_tanh)

tensor([[0., 0., 1., 1., 0., 0., 1., 0.],
        [1., 1., 0., 1., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 0., 1., 1., 0., 1.],
        [0., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 0., 1., 0., 1., 0., 0.],
        [1., 1., 1., 1., 0., 1., 1., 1.]])
tensor([[0.1192, 0.1216, 0.1358, 0.1332, 0.1225, 0.1156, 0.1355, 0.1172],
        [0.1281, 0.1307, 0.1167, 0.1257, 0.1199, 0.1243, 0.1279, 0.1260],
        [0.1192, 0.1216, 0.1192, 0.1169, 0.1225, 0.1317, 0.1355, 0.1336],
        [0.1401, 0.1230, 0.1205, 0.1182, 0.1239, 0.1169, 0.1203, 0.1378],
        [0.1281, 0.1307, 0.1281, 0.1144, 0.1317, 0.1243, 0.1164, 0.1260],
        [0.1181, 0.1205, 0.1326, 0.1301, 0.1363, 0.1286, 0.1179, 0.1162],
        [0.1206, 0.1230, 0.1205, 0.1374, 0.1239, 0.1359, 0.1203, 0.1186],
        [0.1265, 0.1290, 0.1265, 0.1241, 0.1193, 0.1227, 0.1262, 0.1245]])
tensor([[0.0000, 0.0000, 0.7616, 0.7616, 0.0000, 0.0000, 0.7616, 0.000